### PR TITLE
Remove explicit region context from PowerVS Collector

### PR DESCRIPTION
**Pull request by jaywcarman**
Each Power Cloud instance is bound to a single region. The connection
here already has region context.

This commit will require an associated change to the 'ibm-cloud-sdk'
gem.

https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/pull/25

### CODE REVIEW

**Review by Kuldip-Nanda — APPROVED** [review]
as we are getting only specific specific region, this function is not going to be used anywhere. we can remove it.

**Comment by jaywcarman** [comment]
I have a new VCR cassette recorded for the refresher (see Travis fail), but am waiting for the 'ibm-cloud-sdk' gem to be updated before pushing it so we don't break PowerVS refresh.

**Comment by agrare** [comment]
@jaywcarman can you do a cross-repo test with this PR and https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/pull/25 ?

**Comment by jaywcarman** [comment]
> @jaywcarman can you do a cross-repo test with this PR and [IBM-Cloud/ibm-cloud-sdk-ruby#25](https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/pull/25) ?

https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/177

**Comment by jaywcarman** [comment]
Cross repo test is green now:
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/177

**Comment by agrare** [comment]
:+1: awesome, will merge after releasing a new version of ibm-cloud-sdk

**Review by agrare — APPROVED** [review]

**Pull request merged**
