### PR TITLE
VPC create cloud volumes functionality

### PR DESCRIPTION
**Pull request by nasark**
### Task
- added the ability to create cloud volumes through VPC provider

### Reference
- https://cloud.ibm.com/apidocs/vpc#create-volume

### CODE REVIEW

**Comment by nasark** [comment]
@miq-bot add-labels enhancement

**Comment by nasark** [comment]
Note: This is a new enhancement although there is a known issue that occurs even without the PR being applied: https://github.com/ManageIQ/manageiq-ui-classic/issues/7787. At the moment the workaround is to access the form using the dashboard in `Storage -> Volumes`

**Comment by agrare** [comment]
LGTM pending specs

**Comment by nasark** [comment]
@miq-bot remove-label wip

**Comment by nasark** [comment]
@miq-bot add-labels enhancement

**Comment by nasark** [comment]
The travis build is failing with:
```
Failures:

  1) ManageIQ::Providers::IbmCloud::VPC::StorageManager::CloudVolume cloud volume actions #raw_create_volume creates a cloud volume
     Failure/Error: connection.request(:create_volume, :volume_prototype => volume)
     
       #<Double "ManageIQ::Providers::IbmCloud::CloudTools::Vpc"> received :request with unexpected arguments
         expected: (:create_volume, {:volume_prototype=>{:capacity=>10, :iops=>100, :name=>"test", :profile=>{:name=>"custom"}, :zone=>{:name=>"test-zone"}}})
              got: (:create_volume, {:volume_prototype=>{:capacity=>10, :name=>"test", :profile=>{:name=>"5iops-tier"}, :zone=>{:name=>"test-zone"}}})
```

When I run this test locally on my machine it fails intermittently with this error, meaning that there is a mismatch of parameters between the test cases with `custom` and `5iops-tier`. However, this is not the case all the time because the test passes sometimes...

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `morphy` in commit b9eb87080eee82d3193ae8a63b19344a6695a50a.

```text
commit b9eb87080eee82d3193ae8a63b19344a6695a50a
Author: Adam Grare <adam@grare.com>
Date:   Thu Jul 15 13:55:29 2021 -0400

    Merge pull request #242 from nasark/vpc_create_cloud_volumes
    
    VPC create cloud volumes functionality
    
    (cherry picked from commit e6c177fcc9627b369b077644fc0fde9418305cae)
```

**Pull request merged**
