### PR TITLE
Add credential validation to the provider form

### PR DESCRIPTION
**Pull request by agrare**
Screenshot from 2020-09-17 10-54-07

### CODE REVIEW

**Comment by agrare** [comment]
cc @skateman

**Comment by skateman** [comment]
@agrare schema looks fine to me, does the validation actually work?

**Comment by agrare** [comment]
It successfully fails :laughing: I don't have a valid key but it does fail for an invalid api key and prevent submitting the form

**Comment by skateman** [comment]
> It successfully fails  I don't have a valid key but it does fail for an invalid api key and prevent submitting the form

Sounds like it's working then :laughing: can we get some creds to try this out? I have the same issue at the NSX-T provider :confused:

**Comment by jaywcarman** [comment]
It works!

If I try to validate with a working API Key and an invalid PowerVS Service GUID then I get:
`Validation failed: undefined method `crn' for nil:NilClass`

For a future PR would it be possible to catch that error and return a translation? (e.g. invalid GUID for API Key)

**Comment by Fryguy** [comment]
i-have-the-power-he-man-min

**Comment by agrare** [comment]
@jaywcarman yes we should be catching those types of exception and raising better errors

**Review by jaywcarman — APPROVED** [review]

**Pull request merged**
