### PR TITLE
Import Image Form changes to take COS

### PR DESCRIPTION
**Pull request by jdenver23**

### CODE REVIEW

**Comment by agrare** [comment]
@jeffibm @GilbertCherrie can you review the JS changes here?

**Review by GilbertCherrie — APPROVED** [review]

**Comment by GilbertCherrie** [comment]
@agrare I'm not sure how to test this locally but I did a code review and everything looks fine from a code perspective.

**Comment by agrare** [comment]
Thanks @GilbertCherrie 

@jdenver23 looks like you merged master into this branch rather than rebasing this branch on master, https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/405/commits/da298f3fdf3e9243a89dc2ac62784b16b9f205b6
Make sure that you have `git config --global pull.rebase true` set, then `git pull upstream master` to pull the latest changes in.

**Comment by jdenver23** [comment]
> Thanks @GilbertCherrie
> 
> @jdenver23 looks like you merged master into this branch rather than rebasing this branch on master, [da298f3](https://github.com/ManageIQ/manageiq-providers-ibm_cloud/commit/da298f3fdf3e9243a89dc2ac62784b16b9f205b6) Make sure that you have `git config --global pull.rebase true` set, then `git pull upstream master` to pull the latest changes in.
> 
> Check out https://www.manageiq.org/docs/guides/developer_setup/git_workflow

Will do, thank you! Do I need to re-push after or is it just for future notice?

**Comment by agrare** [comment]
> Do I need to re-push after or is it just for future notice?

Yes you should be able to do the `git pull upstream master` and it will drop the merge commit automatically, then just force push to this remote branch

**Comment by agrare** [comment]
@jdenver23 I'm going to squash these two commits for you since one added `+<<<<<<< HEAD` conflict tags and the second removed them.  This doesn't belong in the history and a single commit looks like the way to go here.

**Review by agrare — APPROVED** [review]

**Pull request merged**
