### PR TITLE
Add new VPC regions

### PR DESCRIPTION
**Pull request by jaywcarman**
1. Order VPC regions alphabetically
2. Add new VPC regions

VPC doc listing current regions:
https://cloud.ibm.com/apidocs/vpc/latest#endpoint-url

### CODE REVIEW

**Comment by agrare** [comment]
@jaywcarman is there any programmatic way of retrieving this?  We could auto-update on a schedule like we do with amazon

**Comment by jaywcarman** [comment]
> @jaywcarman is there any programmatic way of retrieving this? We could auto-update on a schedule like we do with amazon

@agrare Great questions - yes there is an API available. It doesn't provide a description field, though:
```json
❯ curl -s -X GET https://br-sao.iaas.cloud.ibm.com/v1/regions\?version\=2024-02-07\&generation\=2 \
    -H "Authorization: Bearer $IBMCLOUD_IAM_TOKEN" | jq .[][:2]                                                                                                                                                                       2024-02-07T15:01:26-06:00 
[
  {
    "name": "au-syd",
    "href": "https://br-sao.iaas.cloud.ibm.com/v1/regions/au-syd",
    "endpoint": "https://au-syd.iaas.cloud.ibm.com",
    "status": "available"
  },
  {
    "name": "br-sao",
    "href": "https://br-sao.iaas.cloud.ibm.com/v1/regions/br-sao",
    "endpoint": "https://br-sao.iaas.cloud.ibm.com",
    "status": "available"
  }
]
```

We could fill that in manually, or even just use the name for the description.

**Comment by agrare** [comment]
> We could fill that in manually, or even just use the name for the description.

Yeah we could even manually add it for any new regions, e.g. https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/.github/workflows/instance_types.yaml will create a new pull request if anything is changed so it doesn't have to be 100% automated but it will alert us when something is changed.

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `quinteros` in commit 1ac163e7e67f4857bbf6c9d3f48ea63f1e5cf7fd.

```text
commit 1ac163e7e67f4857bbf6c9d3f48ea63f1e5cf7fd
Author: Adam Grare <adam@grare.com>
Date:   Wed Feb 7 16:06:40 2024 -0500

    Merge pull request #484 from jaywcarman/add_new_vpc_regions
    
    Add new VPC regions
    
    (cherry picked from commit b002d0bafb64a7927fe9f7943d0192df99950785)
```

**Pull request merged**
