### PR TITLE
adding automatic refresh for ibm vpc

### PR DESCRIPTION
**Pull request by Real-Omar-Afifi**

### CODE REVIEW

**Comment by Real-Omar-Afifi** [comment]
@agrare 15 minutes should be good enough, or should we reduce it to 10?

**Comment by agrare** [comment]
@Real-Omar-Afifi 15 minutes is the standard for providers without an event catcher

**Comment by agrare** [comment]
@Real-Omar-Afifi can you add the same for `ibm_cloud_power_virtual_servers`?

**Comment by agrare** [comment]
This should be added automatically by the provider generator, I'll make that update so we don't forget these again

**Review by agrare — APPROVED** [review]

**Comment by Real-Omar-Afifi** [comment]
@agrare done

**Comment by simaishi** [comment]
Kasparov backport details:

```
$ git log -1
commit bc1883a9898ca62b25970499c444d0f0a1687d09
Author: Adam Grare <agrare@redhat.com>
Date:   Thu Oct 29 14:29:49 2020 -0400

    Merge pull request #110 from Real-Omar-Afifi/master

    adding automatic refresh for ibm vpc

    (cherry picked from commit 26c4831b9bf861d51a61ce1f1c307589f3998371)
```

**Pull request merged**
