### PR TITLE
Additional support for IBM Cloud Databases

### PR DESCRIPTION
**Pull request by nasark**
Continuing from https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/254

Depends on:
* [x] [Add IBM Cloud Databases gem](https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/pull/62)
* [x] [Refactor SDK connections](https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/265)

Ref:
- https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v5

### CODE REVIEW

**Comment by nasark** [comment]
@miq-bot add-labels wip

**Comment by nasark** [comment]
This PR will be updated once all dependencies have been merged

**Comment by nasark** [comment]
@miq-bot remove_label unmergeable, wip

**Comment by nasark** [comment]
@miq-bot add_labels enhancement

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `morphy` in commit 33a07bb447c356a8f90ff75cf5e5a0b21653c725.

```text
commit 33a07bb447c356a8f90ff75cf5e5a0b21653c725
Author: Adam Grare <adam@grare.com>
Date:   Mon Aug 30 15:29:25 2021 -0400

    Merge pull request #262 from nasark/ibm_cloud_db_support
    
    Additional support for IBM Cloud Databases
    
    (cherry picked from commit d577d661cd48d43a2721f4bc3a81c4593e7fcf08)
```

**Pull request merged**
