### PR TITLE
rcfile location fix and ansible role dir. cleanup

### PR DESCRIPTION
**Pull request by iv1111**

### CODE REVIEW

**Comment by iv1111** [comment]
Related PowerVC PR: https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/44

**Comment by jaywcarman** [comment]
Looks like codeclimate "had trouble cloning your git repository". Closing/re-opening to see if works on a second try...

**Review by jaywcarman — COMMENTED** [review]
Looks good @iv1111! I think it's worth fixing the miq-bot and codecliment issues before we merge.

**Review by agrare — APPROVED** [review]

**Review by jaywcarman — APPROVED** [review]
Looks great!

**Pull request merged**
